In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re
import string

In [ ]:
data_fake=pd.read_csv('Fake.csv')
data_true=pd.read_csv('True.csv')

In [ ]:
data_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [ ]:
data_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [ ]:
data_fake["class"] = 0
data_true["class"] = 1

In [ ]:
data_fake.shape,data_true.shape

((23481, 5), (21417, 5))

In [ ]:
for i in range(23480, 23470, -1):
    if i in data_fake.index:
        data_fake.drop([i], axis=0, inplace=True)

for i in range(21416, 21406, -1):
    if i in data_true.index:
        data_true.drop([i], axis=0, inplace=True)

In [ ]:
data_fake_manual_testing = pd.DataFrame()
data_fake_manual_testing['text'] = data_fake['text'][:10]  
data_fake_manual_testing.head(10)

                                                text
0  Donald Trump just couldn t wish all Americans ...
1  House Intelligence Committee Chairman Devin Nu...
2  On Friday, it was revealed that former Milwauk...
3  On Christmas day, Donald Trump announced that ...
4  Pope Francis used his annual Christmas Day mes...
5  The number of cases of cops brutalizing and ki...
6  Donald Trump spent a good portion of his day a...
7  In the wake of yet another court decision that...
8  Many people have raised the alarm regarding th...
9  Just when you might have thought we d get a br...

In [ ]:
data_fake.shape, data_true.shape

((23471, 5), (21407, 5))

In [ ]:
data_fake_manual_testing.head(10)

                                                text
0  Donald Trump just couldn t wish all Americans ...
1  House Intelligence Committee Chairman Devin Nu...
2  On Friday, it was revealed that former Milwauk...
3  On Christmas day, Donald Trump announced that ...
4  Pope Francis used his annual Christmas Day mes...
5  The number of cases of cops brutalizing and ki...
6  Donald Trump spent a good portion of his day a...
7  In the wake of yet another court decision that...
8  Many people have raised the alarm regarding th...
9  Just when you might have thought we d get a br...

In [ ]:
data_true_manual_testing = pd.DataFrame()
data_true_manual_testing['text'] = data_true['text'][:10]  
data_true_manual_testing.head(10)

                                                text
0  WASHINGTON (Reuters) - The head of a conservat...
1  WASHINGTON (Reuters) - Transgender people will...
2  WASHINGTON (Reuters) - The special counsel inv...
3  WASHINGTON (Reuters) - Trump campaign adviser ...
4  SEATTLE/WASHINGTON (Reuters) - President Donal...
5  WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...
6  WEST PALM BEACH, Fla (Reuters) - President Don...
7  The following statements were posted to the ve...
8  The following statements were posted to the ve...
9  WASHINGTON (Reuters) - Alabama Secretary of St...

In [ ]:
data_true_manual_testing.head(10)

                                                text
0  WASHINGTON (Reuters) - The head of a conservat...
1  WASHINGTON (Reuters) - Transgender people will...
2  WASHINGTON (Reuters) - The special counsel inv...
3  WASHINGTON (Reuters) - Trump campaign adviser ...
4  SEATTLE/WASHINGTON (Reuters) - President Donal...
5  WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...
6  WEST PALM BEACH, Fla (Reuters) - President Don...
7  The following statements were posted to the ve...
8  The following statements were posted to the ve...
9  WASHINGTON (Reuters) - Alabama Secretary of St...

In [ ]:
data_merge = pd.concat([data_fake, data_true], axis = 0)
data_merge.head(10)

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0

In [ ]:
data_merge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [ ]:
data = data_merge.drop(['title','subject','date'], axis = 1)

In [ ]:
data.isnull().sum()

text     0
class    0
dtype: int64

In [ ]:
data = data.sample(frac = 1)

In [ ]:
data.head()

                                                    text  class
8979   WASHINGTON (Reuters) - U.S. Democratic preside...      1
15353  BRUSSELS (Reuters) - The European Union wants ...      1
5556   What do Hillary s emails and police murders of...      0
21330  Barack Obama has somehow managed to inspire th...      0
11394  VATICAN CITY (Reuters) - A topless activist fr...      1

In [ ]:
data.reset_index(inplace = True)
data.drop(['index'],axis = 1,inplace = True)

In [ ]:
data.columns

Index(['text', 'class'], dtype='object')

In [ ]:
data.head()

                                                text  class
0  WASHINGTON (Reuters) - U.S. Democratic preside...      1
1  BRUSSELS (Reuters) - The European Union wants ...      1
2  What do Hillary s emails and police murders of...      0
3  Barack Obama has somehow managed to inspire th...      0
4  VATICAN CITY (Reuters) - A topless activist fr...      1

In [ ]:
def wordopt(text):
    # Convert text to lowercase
    text = text.lower()
    
    # Remove text inside square brackets
    text = re.sub(r'\[.*?\]', '', text)
    
    # Remove non-word characters (anything except letters, numbers, and underscore)
    text = re.sub(r"\W", " ", text)
    
    # Remove URLs starting with http(s):// or www.
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    
    # Remove HTML tags
    text = re.sub(r'<.*?>+', '', text)
    
    # Remove punctuation
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    
    # Remove newline characters
    text = re.sub(r'\n', '', text)
    
    # Remove words containing numbers
    text = re.sub(r'\w*\d\w*', '', text)
    
    return text

In [ ]:
data['text'] = data['text'].apply(wordopt)

In [ ]:
x=data['text']
y=data['class']

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(xv_train, y_train)

LogisticRegression()

In [ ]:
pred_lr = LR.predict(xv_test)

In [ ]:
LR.score(xv_test, y_test)

0.9863636363636363

In [ ]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      5832
           1       0.98      0.99      0.99      5388

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [ ]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()
DT.fit(xv_train, y_train)

DecisionTreeClassifier()

In [ ]:
pred_dt = DT.predict(xv_test)

In [ ]:
DT.score(xv_test, y_test)

0.9958110516934047

In [ ]:
print(classification_report(y_test, pred_dt))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5832
           1       1.00      1.00      1.00      5388

    accuracy                           1.00     11220
   macro avg       1.00      1.00      1.00     11220
weighted avg       1.00      1.00      1.00     11220

In [ ]:
def output_label(n):
    if n == 0:
        return "Fake news"
    elif n == 1:
        return "Not a Fake News"

def manual_testing(news):
    testing_news = {"text":[news]}
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(wordopt)
    new_x_test = new_def_test["text"]
    new_xv_test = vectorization.transform(new_x_test)
    pred_LR = LR.predict(new_xv_test)
    pred_DT = DT.predict(new_xv_test)
    return print("\n\nLR Prediction: {} \n\nDT Prediction: {}".format(output_label(pred_LR[0]),
    output_label(pred_DT[0])))

In [ ]:
news = input()
manual_testing(news)

 Time is a priceless, finite resource that cannot be earned back once wasted, making its management essential for a productive life

LR Prediction: Fake news

DT Prediction: Fake news

In [ ]:
from sklearn.linear_model import Ridge


ridge = Ridge(alpha=1.0)
ridge.fit(xv_train, y_train)

pred_ridge = ridge.predict(xv_test)

# Convert continuous output to 0 or 1
pred_ridge_binary = np.where(pred_ridge > 0.5, 1, 0)

print(classification_report(y_test, pred_ridge_binary))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5832
           1       0.99      0.99      0.99      5388

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(xv_train, y_train)

pred_rf = rf.predict(xv_test)

print("Random Forest Accuracy:", accuracy_score(y_test, pred_rf))
print(classification_report(y_test, pred_rf))

Random Forest Accuracy: 0.9907308377896613
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5832
           1       0.99      0.99      0.99      5388

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score

nb = MultinomialNB()
nb.fit(xv_train, y_train)

pred_nb = nb.predict(xv_test)

print("Naive Bayes Accuracy:", accuracy_score(y_test, pred_nb))
print(classification_report(y_test, pred_nb))

Naive Bayes Accuracy: 0.9372549019607843
              precision    recall  f1-score   support

           0       0.93      0.95      0.94      5832
           1       0.94      0.92      0.93      5388

    accuracy                           0.94     11220
   macro avg       0.94      0.94      0.94     11220
weighted avg       0.94      0.94      0.94     11220

In [ ]:
from sklearn.svm import LinearSVC

svm = LinearSVC()
svm.fit(xv_train, y_train)

pred_svm = svm.predict(xv_test)

print("SVM Accuracy:", accuracy_score(y_test, pred_svm))
print(classification_report(y_test, pred_svm))

SVM Accuracy: 0.9941176470588236
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5832
           1       0.99      0.99      0.99      5388

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220